### PR TITLE
Change function name in readme example

### PR DESCRIPTION
**Pull request by Archmonger**
Just realized the name of the example in the readme is `App`. However, we really want to focus on giving users a more realistic component name to get them on the right track.

And truthfully, calling it `App` is a misnomer. The function itself is a component, even if `run()` is creating an ASGI app on the backend.

### CODE REVIEW

**Comment by Archmonger** [comment]
Side note, the new changelog check CI is fairly annoying. I think a "Welcome Message" CI reminding users to add a changelog entry if needed is a better approach.

**Comment by rmorshea** [comment]
Yeah the changelog CI actions is definitely broken. Happy to just go with a welcome message on new MRs instead.

**Comment by Archmonger** [comment]
This current PR is ready for review.

A separate PR created to modify the CI: #752

**Review by rmorshea — APPROVED** [review]

**Comment by Archmonger** [comment]
Yep, greetings message is broken.

**Comment by rmorshea** [comment]
It seems like this might be a more general problem with permissions around forked repos.

**Review by rmorshea — APPROVED** [review]

**Comment by Archmonger** [comment]
I think I'll create my own "Greetings CI" repo to handle this without permissions.

**Review by rmorshea — APPROVED** [review]

**Pull request merged**
