### PR TITLE
bypass jsonpatch

### PR DESCRIPTION
**Pull request by rmorshea**
The `jsonpatch` library is [broken](https://github.com/stefankoegl/python-json-patch/issues/138) and it seems like there's no one to maintain it. We should just avoid JSON Patch entirely since, so long as you're careful about what components you re-render, diffing is not usually necessary. In a future release, the client will stop using JSON patch altogether.

## Checklist

Please update this checklist as you complete each item:

- [ ] Tests have been included for all bug fixes or added functionality.
- [x] The `changelog.rst` has been updated with any significant changes.
- [x] GitHub Issues which may be closed by this Pull Request have been linked.

### CODE REVIEW

**Comment by Archmonger** [comment]
How certain are we that the current exception (`onChange` missing) detected on idom-team/django-idom#86 is related to Json patch?

**Comment by rmorshea** [comment]
I'm pretty certain. Could you test using this branch though to be sure? `pip install git+https://github.com/idom-team/idom@bypass-jsonpatch`

**Review by Archmonger — CHANGES_REQUESTED** [review]
This does not fix the issue on `django-idom`, tested via `pip install git+`

**Comment by rmorshea** [comment]
On what branch is this happening?

**Comment by Archmonger** [comment]
Branch: https://github.com/idom-team/django-idom/pull/86 (idom-team/django-idom@use_database)
Code Sample; Manually running the `use_mutation` and `use_database` tests via `python test/manage.py runserver` and inspecting in browser
Error message: Yes it is [the same](https://github.com/idom-team/django-idom/pull/86#issuecomment-1244703340) even when using this bypass jsonpatch branch.

**Review by Archmonger — APPROVED** [review]
Confirmed working.

**Comment by rmorshea** [comment]
will release tomorrow

**Pull request merged**
