### PR TITLE
Form serialize

### PR DESCRIPTION
**Pull request by acivitillo**
closes: #573

### CODE REVIEW

**Comment by rmorshea** [comment]
I'll have time to take a look at this over the weekend

**Comment by acivitillo** [comment]
yes, do note it's broken, I send you the diff to understand how you want to approach `form` serialization as `form` contains multiple elements

**Comment by rmorshea** [comment]
@acivitillo, I've fixed up the serialization implementation. There were a couple things that were wrong about my suggestions on how to do this.  

Could you address the tests? In addition to the `elements` attribute, I've serialized the `name` attribute too.

**Comment by Archmonger** [comment]
Serializing form attributes into the URL would be a nice feature if we could get it working cleanly. Might help with form value persistence upon WS disconnect?

We should do some investigation later down the line to figure out what React apps typically do for forms.

**Comment by rmorshea** [comment]
To properly handle form URLs we'll need [a wrapper](https://github.com/idom-team/idom-router/issues/7) around the standard form element.

**Comment by Archmonger** [comment]
What do we plan on doing about file fields

**Comment by rmorshea** [comment]
Not entirely sure. We can address separately to address https://github.com/idom-team/idom/issues/574.

**Review by Archmonger — DISMISSED** [review]

**Pull request merged**
