### PR TITLE
Fix idom.run and more renaming of server to backend

### PR DESCRIPTION
**Pull request by rmorshea**
# Description

Renames `idom.server` to `idom.backend` also renamed `ServerFixture` to `BackendFixture` + `DisplayFixture.server` to `DisplayFixture.backend`.

# Checklist:

Please update this checklist as you complete each item:

- [x] Tests have been included for all bug fixes or new functionality.
- [x] The `changelog.rst` has been updated with any significant changes.
- [ ] GitHub Issues which may be closed by this Pull Request have been linked.

### CODE REVIEW

**Comment by Archmonger** [comment]
@rmorshea Should we add a task to v2 to have functional tetsts for `idom.run`?

**Comment by rmorshea** [comment]
It actually looks like there is a test. Not sure why it didn't catch it.

**Comment by Archmonger** [comment]
I wasn't able to locate the test in the repo. But perhaps it's not checking running via the default (unspecified) server implementation?

**Comment by rmorshea** [comment]
Ah, yup. [That's exactly it](https://github.com/idom-team/idom/blob/main/tests/test_server/test_utils.py#L30).

**Comment by rmorshea** [comment]
The trouble is that we have to specify the implementation as Flask because the others don't play nice in threads.

**Pull request merged**
